#!/bin/bash

# Ensure the temporary directory exists
TEMP_DIR='./tmp';
[[ ! -d $TEMP_DIR ]] && mkdir -p $TEMP_DIR;

# Capture the UUID (it is used multiple times)
UUID=`uuidgen`;

# Launch the application
ARGS="$@" CLIENT_FILE="$TEMP_DIR/$UUID.client" screen -c .screenrc-hijack;
