#!/usr/bin/env bash

port=${PORT:-4567};
pid_file=${PID_FILE:-./tmp/puma.pid};
rackup_config=${RACKUP_CONFIG:-./config/config.ru};

if [ -n "$DAEMONIZE" ];
then
  puma --port $port -d --pidfile $pid_file $rackup_config;
else
  puma --port $port $rackup_config;
fi
